import React, { useState } from 'react';
import { Download, Printer, Copy, Check, X, ShieldAlert, FileText, CheckCircle2, FileDown, Loader2 } from 'lucide-react';
import { ScanResult } from '../types';
import { downloadScanReportPdf } from '../utils/pdfGenerator';

interface ShareReportModalProps {
  scanResult: ScanResult;
  isOpen: boolean;
  onClose: () => void;
}

export const ShareReportModal: React.FC<ShareReportModalProps> = ({
  scanResult,
  isOpen,
  onClose,
}) => {
  const [copied, setCopied] = useState(false);
  const [isDownloadingPdf, setIsDownloadingPdf] = useState(false);

  if (!isOpen) return null;

  const handleDownloadPdf = async () => {
    try {
      setIsDownloadingPdf(true);
      await downloadScanReportPdf(scanResult);
    } catch (err) {
      console.error('PDF export error:', err);
    } finally {
      setIsDownloadingPdf(false);
    }
  };

  const generateMarkdownReport = () => {
    return `# SCAMSHIELD AI — FORENSIC SECURITY REPORT
Incident ID: ${scanResult.scan_id}
Date: ${new Date(scanResult.timestamp).toUTCString()}
Scan Type: ${scanResult.scan_type}
Input Mode: ${scanResult.input_type}

--------------------------------------------------
SCAM THREAT INDEX: ${scanResult.threat_score} / 100
VERDICT: ${scanResult.risk_level} RISK
SCAM TYPES: ${scanResult.scam_types.join(', ')}
--------------------------------------------------

### WHY WE FLAGGED THIS:
${scanResult.red_flags.map((rf) => `- [${rf.severity}] ${rf.label}: ${rf.explanation}`).join('\n')}

### EXTRACTED ENTITIES:
- Claimed Company: ${scanResult.extracted_entities.company_name || 'N/A'}
- Recruiter Name: ${scanResult.extracted_entities.recruiter_name || 'N/A'}
- Recruiter Email: ${scanResult.extracted_entities.email || 'N/A'}
- Payment Demands: ${scanResult.extracted_entities.payment_requests.join(', ') || 'None'}
- UPI IDs: ${scanResult.extracted_entities.upi_ids.join(', ') || 'None'}

### IDENTITY CROSS-CHECK:
${scanResult.company_verification ? `- Official Domain: ${scanResult.company_verification.officialDomain}
- Recruiter Email Domain: ${scanResult.company_verification.recruiterEmailDomain}
- Status: ${scanResult.company_verification.status}
- Forensic Note: ${scanResult.company_verification.details}` : 'N/A'}

### RECOMMENDED ACTION STEPS:
${scanResult.recommendations.map((r, i) => `${i + 1}. [${r.severity}] ${r.text}`).join('\n')}

Report generated by ScamShield AI Platform. Verify before trusting.
`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateMarkdownReport());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md">
      <div className="w-full max-w-3xl bg-slate-950 border border-slate-800 rounded-2xl shadow-2xl max-h-[90vh] flex flex-col overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800 bg-slate-900/80">
          <div className="flex items-center gap-2.5">
            <FileText className="w-5 h-5 text-cyan-400" />
            <div>
              <h3 className="text-sm font-bold text-white uppercase tracking-wider">
                Official Security Forensic Report
              </h3>
              <p className="text-[11px] text-slate-400 font-mono">
                Report Reference #{scanResult.scan_id}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2 flex-wrap">
            <button
              onClick={handleDownloadPdf}
              disabled={isDownloadingPdf}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold text-xs transition-all disabled:opacity-50"
            >
              {isDownloadingPdf ? (
                <Loader2 className="w-3.5 h-3.5 animate-spin" />
              ) : (
                <FileDown className="w-3.5 h-3.5" />
              )}
              <span>{isDownloadingPdf ? 'Generating...' : 'Download PDF'}</span>
            </button>

            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 text-xs font-medium transition-all"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy Text'}</span>
            </button>

            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700 text-xs font-medium transition-all"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print</span>
            </button>

            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-all ml-1"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Report Content Preview (printable area) */}
        <div id="printable-report-area" className="flex-1 p-6 sm:p-8 overflow-y-auto font-sans space-y-6 bg-slate-950 text-slate-200">
          {/* Top Banner */}
          <div className="flex flex-wrap items-center justify-between gap-4 p-4 rounded-xl bg-slate-900 border border-slate-800">
            <div>
              <div className="text-xs font-mono uppercase text-cyan-400 font-bold mb-1">
                ScamShield AI Incident Assessment
              </div>
              <div className="text-lg font-bold text-white">
                {scanResult.scan_type === 'JOB_OFFER' ? 'Employment Offer Integrity Audit' : 'Rental Deposit Fraud Audit'}
              </div>
              <div className="text-xs text-slate-400 mt-1 font-mono">
                Generated: {new Date(scanResult.timestamp).toLocaleString()}
              </div>
            </div>

            <div className="text-right">
              <div className="text-xs font-mono uppercase text-slate-400">Scam Threat Index</div>
              <div className={`text-3xl font-extrabold font-mono ${scanResult.risk_level === 'HIGH' ? 'text-red-400' : scanResult.risk_level === 'SUSPICIOUS' ? 'text-amber-400' : 'text-emerald-400'}`}>
                {scanResult.threat_score} / 100
              </div>
              <span className="text-[10px] font-mono font-bold uppercase px-2 py-0.5 rounded bg-slate-800 text-slate-300 border border-slate-700">
                {scanResult.risk_level} RISK
              </span>
            </div>
          </div>

          {/* Key Findings */}
          <div>
            <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">
              Detected Red Flags ({scanResult.red_flags.length})
            </h4>
            <div className="space-y-2">
              {scanResult.red_flags.map((rf) => (
                <div key={rf.id} className="p-3 rounded-lg bg-slate-900/60 border border-slate-800/80 text-xs">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="font-bold text-red-400 font-mono">[{rf.severity}]</span>
                    <span className="font-semibold text-slate-200">{rf.label}</span>
                  </div>
                  <div className="text-slate-400">{rf.explanation}</div>
                </div>
              ))}
            </div>
          </div>

          {/* Identity Matrix */}
          {scanResult.company_verification && (
            <div>
              <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">
                Identity Verification Matrix
              </h4>
              <div className="p-3.5 rounded-lg bg-slate-900/60 border border-slate-800 text-xs space-y-1.5 font-mono">
                <div><span className="text-slate-500">Claimed Company:</span> {scanResult.company_verification.claimedCompany || 'N/A'}</div>
                <div><span className="text-slate-500">Enterprise Domain:</span> {scanResult.company_verification.officialDomain}</div>
                <div><span className="text-slate-500">Recruiter Domain:</span> {scanResult.company_verification.recruiterEmailDomain}</div>
                <div><span className="text-slate-500">Integrity Status:</span> {scanResult.company_verification.status}</div>
              </div>
            </div>
          )}

          {/* Safety Recommendations */}
          <div>
            <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">
              Mandatory Safety Guidance
            </h4>
            <ul className="space-y-1.5 text-xs text-slate-300">
              {scanResult.recommendations.map((rec) => (
                <li key={rec.id} className="flex items-start gap-2">
                  <span className="text-cyan-400">•</span>
                  <span>{rec.text}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-3 border-t border-slate-800 bg-slate-900/80 text-[11px] text-slate-500 flex items-center justify-between">
          <span>ScamShield AI • Deterministic Zero-Trust Audit Engine</span>
          <span className="font-mono">Verification Hash: {scanResult.scan_id.slice(0, 16)}</span>
        </div>
      </div>
    </div>
  );
};
